import type { InsertProject } from "@workspace/db";

type SeedProject = Omit<InsertProject, "isAutoDiscovered" | "reviewStatus" | "discoveredAt" | "confidenceScore" | "extractionSource">;

export const SEED_PROJECTS: SeedProject[] = [

  // ── ANGOLA (10 projects) ────────────────────────────────────────────────────
  {
    projectName: "Soyo Combined Cycle Gas Power Plant",
    country: "Angola", region: "Central Africa", technology: "Oil & Gas",
    status: "Operational", dealSizeUsdMn: 2000, capacityMw: 750,
    announcedYear: 2011,
    developer: "GE / Chevron Angola",
    investors: "Chevron, GE, Sonangol",
    description: "750 MW combined cycle gas turbine power plant in Soyo, northern Angola, built to supply electricity to industrial and domestic consumers. Co-developed by Chevron and GE, it remains one of Angola's largest power generation assets.",
    latitude: -6.13, longitude: 12.37,
    sourceUrl: "https://www.ge.com/news/press-releases/ge-and-chevron-sign-agreement-angola-power-plant",
  },
  {
    projectName: "Laúca Hydroelectric Dam",
    country: "Angola", region: "Central Africa", technology: "Hydro",
    status: "Operational", dealSizeUsdMn: 4300, capacityMw: 2070,
    announcedYear: 2012,
    developer: "Odebrecht / Ministerio de Energia e Aguas",
    investors: "BNDES, China Eximbank, Odebrecht",
    description: "2,070 MW hydroelectric dam on the Kwanza River, the largest power plant in Angola and one of the biggest in Africa. Financed by Brazilian development bank BNDES and built by Odebrecht.",
    latitude: -10.37, longitude: 15.90,
    sourceUrl: "https://www.bloomberg.com/news/articles/angola-lauca-dam",
  },
  {
    projectName: "Cambambe Hydropower Expansion",
    country: "Angola", region: "Central Africa", technology: "Hydro",
    status: "Operational", dealSizeUsdMn: 650, capacityMw: 960,
    announcedYear: 2010,
    developer: "PRODEL / Alstom",
    investors: "China Eximbank, Angolan Government",
    description: "Rehabilitation and expansion of the Cambambe hydropower plant on the Kwanza River, increasing capacity from 260 MW to 960 MW. Financed primarily through Chinese development lending.",
    latitude: -9.49, longitude: 14.77,
    sourceUrl: "https://www.reuters.com/angola-cambambe-hydropower",
  },
  {
    projectName: "Caculo Cabaça Hydropower Project",
    country: "Angola", region: "Central Africa", technology: "Hydro",
    status: "Under Construction", dealSizeUsdMn: 4500, capacityMw: 2172,
    announcedYear: 2016,
    developer: "Gezhouba Group / Ministerio de Energia e Aguas",
    investors: "China Eximbank, Angolan Government",
    description: "2,172 MW hydroelectric project on the Kwanza River, slated to become Angola's largest power plant upon completion. Construction led by China Gezhouba Group with Chinese financing.",
    latitude: -10.22, longitude: 15.55,
    sourceUrl: "https://www.afdb.org/angola-caculo-cabaca",
  },
  {
    projectName: "Angola LNG Plant (Soyo)",
    country: "Angola", region: "Central Africa", technology: "Oil & Gas",
    status: "Operational", dealSizeUsdMn: 10000, capacityMw: null,
    announcedYear: 2007,
    developer: "Chevron, Sonangol, BP, Total, ENI",
    investors: "Chevron (36.4%), Sonangol (22.8%), BP (13.6%), Total (13.6%), ENI (13.6%)",
    description: "5.2 million tonne per annum LNG export facility at Soyo, Angola, operated by a consortium led by Chevron and Sonangol. One of the largest energy investments in sub-Saharan Africa.",
    latitude: -6.13, longitude: 12.37,
    sourceUrl: "https://www.chevron.com/angola-lng",
  },
  {
    projectName: "Block 15/06 Agogo Deep-Water Oil Field",
    country: "Angola", region: "Central Africa", technology: "Oil & Gas",
    status: "Operational", dealSizeUsdMn: 6000, capacityMw: null,
    announcedYear: 2014,
    developer: "ENI / Sonangol",
    investors: "ENI (35.5%), Sonangol (35%), SSI (25%), Falcon Oil (4.5%)",
    description: "Deep-water oil development in Angola's Block 15/06, with the Agogo field producing over 150,000 barrels/day. Operated by ENI as part of a broader FPSO development programme.",
    latitude: -8.50, longitude: 11.50,
    sourceUrl: "https://www.eni.com/en-IT/operations/angola.html",
  },
  {
    projectName: "Quilemba Solar Park",
    country: "Angola", region: "Central Africa", technology: "Solar",
    status: "Development", dealSizeUsdMn: 38, capacityMw: 25,
    announcedYear: 2020,
    developer: "PRODEL / Quevedo Solar",
    investors: "AfDB, SEFA",
    description: "25 MW utility-scale solar PV project near Quilemba in southern Angola, aimed at extending electricity access. Supported by the AfDB Sustainable Energy Fund for Africa.",
    latitude: -15.75, longitude: 13.90,
    sourceUrl: "https://www.afdb.org/en/projects-and-operations/projects/angola-quilemba-solar",
  },
  {
    projectName: "Namibe Wind Farm",
    country: "Angola", region: "Central Africa", technology: "Wind",
    status: "Development", dealSizeUsdMn: null, capacityMw: 100,
    announcedYear: 2019,
    developer: "Ministerio de Energia e Aguas",
    investors: null,
    description: "Planned 100 MW wind energy project in Namibe province on the Angolan coast, capitalising on strong onshore wind resources. Part of Angola's renewable energy diversification programme.",
    latitude: -15.19, longitude: 12.15,
    sourceUrl: "https://angola-energy.gov.ao/namibe-wind",
  },
  {
    projectName: "Biocom Bioenergy Angola",
    country: "Angola", region: "Central Africa", technology: "Bioenergy",
    status: "Operational", dealSizeUsdMn: 500, capacityMw: 35,
    announcedYear: 2011,
    developer: "Biocom (Odebrecht / Sonangol / Damer)",
    investors: "BNDES, Odebrecht, Sonangol",
    description: "Integrated sugar-ethanol biorefinery and 35 MW co-generation plant in Malanje, Angola. Processes sugarcane for fuel ethanol and electricity, producing around 250 million litres of ethanol annually.",
    latitude: -9.54, longitude: 16.34,
    sourceUrl: "https://www.biocom.ao",
  },
  {
    projectName: "Tombwa Solar Photovoltaic Project",
    country: "Angola", region: "Central Africa", technology: "Solar",
    status: "Announced", dealSizeUsdMn: 45, capacityMw: 30,
    announcedYear: 2022,
    developer: "PRODEL",
    investors: "AfDB, Angolan Government",
    description: "Planned 30 MW solar PV plant near Tombwa in Namibe Province, southern Angola. Part of a broader PRODEL programme to deploy 200 MW of solar capacity across underserved southern regions.",
    latitude: -15.80, longitude: 11.85,
    sourceUrl: "https://prodel.gov.ao/tombwa-solar",
  },

  // ── ALGERIA (8 projects) ────────────────────────────────────────────────────
  {
    projectName: "Hassi R'Mel Integrated Solar Gas Power Plant",
    country: "Algeria", region: "North Africa", technology: "Solar",
    status: "Operational", dealSizeUsdMn: 315, capacityMw: 150,
    announcedYear: 2007,
    developer: "New Energy Algeria (NEAL) / Sonelgaz / SIM",
    investors: "AFD, EIB, KfW, JICA",
    description: "150 MW integrated solar-gas combined cycle power plant at Hassi R'Mel, one of Africa's first utility-scale hybrid solar projects. A 25 MW solar field supplements a 120 MW gas turbine, reducing fuel consumption.",
    latitude: 32.93, longitude: 3.27,
    sourceUrl: "https://www.iea.org/reports/hassi-rmel",
  },
  {
    projectName: "Adrar Wind Farm",
    country: "Algeria", region: "North Africa", technology: "Wind",
    status: "Operational", dealSizeUsdMn: 81, capacityMw: 10,
    announcedYear: 2013,
    developer: "Sonelgaz / Théolia",
    investors: "Sonelgaz, AFD",
    description: "Algeria's first utility-scale wind farm, located near Adrar in the Sahara. Developed by Sonelgaz with technical support from French firm Théolia, demonstrating commercial wind potential in the Algerian interior.",
    latitude: 27.87, longitude: -0.29,
    sourceUrl: "https://www.theolia.com/en/projects/adrar",
  },
  {
    projectName: "Ghardaia Hybrid Solar PV Plant",
    country: "Algeria", region: "North Africa", technology: "Solar",
    status: "Operational", dealSizeUsdMn: 12, capacityMw: 1.1,
    announcedYear: 2011,
    developer: "CDER / Sonelgaz",
    investors: "Algerian Government",
    description: "Pilot hybrid solar PV and diesel mini-grid at Ghardaïa, serving as a demonstration project for off-grid renewable integration in remote Algerian communities.",
    latitude: 32.49, longitude: 3.67,
    sourceUrl: "https://www.cder.dz/ghardaia-solar",
  },
  {
    projectName: "In Salah Gas Project (BP/Sonatrach)",
    country: "Algeria", region: "North Africa", technology: "Oil & Gas",
    status: "Operational", dealSizeUsdMn: 3000, capacityMw: null,
    announcedYear: 2001,
    developer: "BP / Statoil / Sonatrach",
    investors: "BP (33.15%), Statoil (33.15%), Sonatrach (33.7%)",
    description: "Major natural gas production facility in the Sahara Desert, one of the world's largest gas developments. Produces around 9 billion cubic metres per year and was also the site of a pioneering CCS (carbon capture) pilot.",
    latitude: 27.21, longitude: 2.47,
    sourceUrl: "https://www.bp.com/in-salah-gas",
  },
  {
    projectName: "Tafouk 1 Solar Programme",
    country: "Algeria", region: "North Africa", technology: "Solar",
    status: "Development", dealSizeUsdMn: 800, capacityMw: 1000,
    announcedYear: 2022,
    developer: "Sonelgaz / Shariket Kahraba wa Takat Moutadjadida (SKTM)",
    investors: "Sonelgaz, EIB, AfDB",
    description: "Algeria's flagship 1 GW solar programme, part of the national target of 15 GW renewables by 2035. The Tafouk 1 tender attracted bids from major international developers and marks Algeria's re-entry into large-scale solar procurement.",
    latitude: 28.00, longitude: 2.00,
    sourceUrl: "https://www.reuters.com/algeria-tafouk-solar",
  },
  {
    projectName: "South-West Gas Pipeline (Trans-Saharan)",
    country: "Algeria", region: "North Africa", technology: "Oil & Gas",
    status: "Development", dealSizeUsdMn: 4000, capacityMw: null,
    announcedYear: 2009,
    developer: "Sonatrach / NNPC",
    investors: "Algeria, Nigeria, Niger governments",
    description: "Proposed Trans-Saharan Gas Pipeline (TSGP) to transport Nigerian gas 4,128 km through Niger to Algeria and onward to Europe. Revived as a priority infrastructure corridor following the European energy crisis.",
    latitude: 20.00, longitude: 5.00,
    sourceUrl: "https://www.afdb.org/trans-saharan-gas-pipeline",
  },
  {
    projectName: "Arzew LNG Complex Expansion",
    country: "Algeria", region: "North Africa", technology: "Oil & Gas",
    status: "Operational", dealSizeUsdMn: 2500, capacityMw: null,
    announcedYear: 2013,
    developer: "Sonatrach",
    investors: "Sonatrach, Algerian Government",
    description: "Expansion of Algeria's Arzew LNG terminal complex, which is among the world's oldest and largest, increasing liquefaction and export capacity for European markets.",
    latitude: 35.85, longitude: -0.31,
    sourceUrl: "https://www.sonatrach.dz/arzew-lng",
  },
  {
    projectName: "Algeria National 4,000 MW Solar Programme",
    country: "Algeria", region: "North Africa", technology: "Solar",
    status: "Development", dealSizeUsdMn: 2500, capacityMw: 4000,
    announcedYear: 2020,
    developer: "Ministry of Energy / SKTM",
    investors: "Algerian Government, EIB",
    description: "National renewable energy programme targeting 4,000 MW of solar by 2024 and 15,000 MW by 2035. Includes distributed rooftop solar, utility-scale PV tenders, and hybrid wind-solar projects across Algeria.",
    latitude: 28.00, longitude: 3.00,
    sourceUrl: "https://unfccc.int/algeria-ndc-solar",
  },

  // ── NAMIBIA (6 projects) ────────────────────────────────────────────────────
  {
    projectName: "Hyphen Green Hydrogen Project",
    country: "Namibia", region: "Southern Africa", technology: "Hydrogen",
    status: "Development", dealSizeUsdMn: 10000, capacityMw: 5000,
    announcedYear: 2021,
    developer: "Hyphen Hydrogen Energy",
    investors: "Nicholas Holdings, Enertrag, Namibian Government",
    description: "Namibia's flagship green hydrogen project in the Tsau //Khaeb National Park, targeting 5 GW of wind and solar to produce ammonia for export to Europe. One of Africa's largest single clean energy investments.",
    latitude: -27.50, longitude: 16.50,
    sourceUrl: "https://www.hyphen-energy.com",
  },
  {
    projectName: "Daures Green Hydrogen Hub",
    country: "Namibia", region: "Southern Africa", technology: "Hydrogen",
    status: "Development", dealSizeUsdMn: 4600, capacityMw: 3000,
    announcedYear: 2022,
    developer: "Enertrag / Namibia Green Hydrogen",
    investors: "Enertrag, KfW, DBSA",
    description: "3 GW green hydrogen and ammonia production hub in the Namib Desert, developed by Enertrag and partially financed by German development bank KfW as part of the H2Global programme.",
    latitude: -21.00, longitude: 14.50,
    sourceUrl: "https://www.enertrag.com/namibia-green-hydrogen",
  },
  {
    projectName: "Kudu Gas Field Development",
    country: "Namibia", region: "Southern Africa", technology: "Oil & Gas",
    status: "Suspended", dealSizeUsdMn: 1200, capacityMw: 800,
    announcedYear: 2003,
    developer: "NamPower / Tullow Oil",
    investors: "NamPower, Tullow Oil, DBSA",
    description: "Offshore gas field development and 800 MW gas-to-power plant proposed to supply Namibia and South Africa. Suspended due to financing difficulties and offshore technical challenges.",
    latitude: -28.50, longitude: 15.30,
    sourceUrl: "https://www.nampower.com.na/kudu",
  },
  {
    projectName: "Diaz Wind Farm",
    country: "Namibia", region: "Southern Africa", technology: "Wind",
    status: "Development", dealSizeUsdMn: 120, capacityMw: 44,
    announcedYear: 2018,
    developer: "Namibia IPP Wind Energy Consortium",
    investors: "IFC, NamPower, FMO",
    description: "44 MW onshore wind farm near Lüderitz on Namibia's Atlantic coast, the country's first utility-scale wind project. Developed under Namibia's inaugural IPP programme with IFC backing.",
    latitude: -26.68, longitude: 15.16,
    sourceUrl: "https://www.ifc.org/namibia-diaz-wind",
  },
  {
    projectName: "Khan Solar Park",
    country: "Namibia", region: "Southern Africa", technology: "Solar",
    status: "Development", dealSizeUsdMn: 80, capacityMw: 50,
    announcedYear: 2019,
    developer: "AECOM / NamPower",
    investors: "KfW, NamPower",
    description: "50 MW solar PV project in the Khan River valley near Arandis, leveraging Namibia's world-class solar irradiance. Supported by German KfW development finance.",
    latitude: -22.25, longitude: 15.05,
    sourceUrl: "https://nampower.com.na/khan-solar",
  },
  {
    projectName: "Baynes Hydropower Project",
    country: "Namibia", region: "Southern Africa", technology: "Hydro",
    status: "Development", dealSizeUsdMn: 1200, capacityMw: 600,
    announcedYear: 2010,
    developer: "NamPower / ZESA",
    investors: "AfDB, DBSA, NamPower, ZESA",
    description: "600 MW run-of-river hydropower project on the Kunene River at the Namibia-Angola border. A binational project to supply both countries; currently at advanced feasibility stage with AfDB co-financing.",
    latitude: -17.13, longitude: 12.53,
    sourceUrl: "https://www.afdb.org/baynes-hydropower",
  },

  // ── TUNISIA (5 projects) ────────────────────────────────────────────────────
  {
    projectName: "TuNur Solar Export Project",
    country: "Tunisia", region: "North Africa", technology: "Solar",
    status: "Development", dealSizeUsdMn: 1600, capacityMw: 4500,
    announcedYear: 2017,
    developer: "TuNur Limited / Nur Energie",
    investors: "TuNur, Mainstream RP, EIB",
    description: "Concentrating solar power (CSP) mega-project in the Saharan region of Tunisia, designed to export clean electricity to Europe via an HVDC subsea cable to Malta and Italy. One of Europe's most ambitious solar import projects.",
    latitude: 33.00, longitude: 9.00,
    sourceUrl: "https://www.tunur.tn",
  },
  {
    projectName: "Sidi Daoud Wind Farm",
    country: "Tunisia", region: "North Africa", technology: "Wind",
    status: "Operational", dealSizeUsdMn: 60, capacityMw: 54,
    announcedYear: 2000,
    developer: "STEG",
    investors: "AfDB, AFD, STEG",
    description: "Tunisia's first utility-scale wind farm at Sidi Daoud, Cap Bon. Operational since 2000 and expanded to 54 MW, financed by AfDB and the French Development Agency.",
    latitude: 37.02, longitude: 10.97,
    sourceUrl: "https://www.afdb.org/sidi-daoud",
  },
  {
    projectName: "Tozeur Nefta Solar PV Park",
    country: "Tunisia", region: "North Africa", technology: "Solar",
    status: "Operational", dealSizeUsdMn: 15, capacityMw: 10,
    announcedYear: 2017,
    developer: "STEG",
    investors: "AfDB, STEG",
    description: "10 MW solar PV plant at Tozeur in southern Tunisia, the country's first utility-scale solar plant and a milestone in Tunisia's transition to clean energy.",
    latitude: 33.92, longitude: 8.14,
    sourceUrl: "https://www.steg.com.tn/tozeur-solar",
  },
  {
    projectName: "Tataouine Wind Farm (Engie)",
    country: "Tunisia", region: "North Africa", technology: "Wind",
    status: "Development", dealSizeUsdMn: 200, capacityMw: 120,
    announcedYear: 2019,
    developer: "Engie / GasTech",
    investors: "Engie, IFC, PROPARCO",
    description: "120 MW wind project in Tataouine governorate in southern Tunisia. Developed by Engie with IFC and Proparco financing, representing one of Tunisia's first large-scale IPP wind projects.",
    latitude: 32.93, longitude: 10.45,
    sourceUrl: "https://www.engie.com/tunisia-wind",
  },
  {
    projectName: "STEG 500 MW Solar Concession Programme",
    country: "Tunisia", region: "North Africa", technology: "Solar",
    status: "Announced", dealSizeUsdMn: 400, capacityMw: 500,
    announcedYear: 2023,
    developer: "STEG / Ministry of Energy",
    investors: "EIB, KfW, AfDB",
    description: "500 MW solar PV competitive tender by Tunisian state utility STEG to accelerate renewable energy deployment. Part of Tunisia's national goal of 35% renewable electricity by 2030.",
    latitude: 33.50, longitude: 9.50,
    sourceUrl: "https://www.steg.com.tn/solar-concession",
  },

  // ── LIBYA (4 projects) ─────────────────────────────────────────────────────
  {
    projectName: "Bahr Essalam Gas Field (ENI / Repsol)",
    country: "Libya", region: "North Africa", technology: "Oil & Gas",
    status: "Operational", dealSizeUsdMn: 6000, capacityMw: null,
    announcedYear: 2004,
    developer: "ENI / Repsol / NOC",
    investors: "ENI (50%), Repsol (50%), NOC",
    description: "Offshore gas field and pipeline supplying the Greenstream subsea gas pipeline to Italy. Bahr Essalam is one of Libya's major gas export assets, operated by ENI in partnership with Spain's Repsol.",
    latitude: 32.50, longitude: 12.00,
    sourceUrl: "https://www.eni.com/libya-bahr-essalam",
  },
  {
    projectName: "Waha Oil Concession",
    country: "Libya", region: "North Africa", technology: "Oil & Gas",
    status: "Operational", dealSizeUsdMn: 3000, capacityMw: null,
    announcedYear: 1969,
    developer: "Waha Oil Company (ConocoPhillips / Marathon / Hess / NOC)",
    investors: "NOC (59.18%), ConocoPhillips, Marathon, Hess",
    description: "One of Libya's largest oil-producing consortia, comprising multiple fields in the Sirte Basin. Post-conflict restoration of production capacity has drawn over $3B in upstream investment since 2020.",
    latitude: 28.00, longitude: 18.00,
    sourceUrl: "https://www.conocophillips.com/operations/africa/libya",
  },
  {
    projectName: "Derna Wind Farm",
    country: "Libya", region: "North Africa", technology: "Wind",
    status: "Suspended", dealSizeUsdMn: 290, capacityMw: 150,
    announcedYear: 2009,
    developer: "GECOL / Iberdrola",
    investors: "Libyan Government, Iberdrola",
    description: "150 MW wind farm proposed near Derna on Libya's northeastern coast, suspended due to conflict. Pre-conflict wind resource assessments showed excellent viability; revival is pending political stabilisation.",
    latitude: 32.76, longitude: 22.64,
    sourceUrl: "https://www.gecol.ly/derna-wind",
  },
  {
    projectName: "Ubari Solar Power Plant",
    country: "Libya", region: "North Africa", technology: "Solar",
    status: "Development", dealSizeUsdMn: 600, capacityMw: 500,
    announcedYear: 2012,
    developer: "GECOL / EETC",
    investors: "Libyan Government",
    description: "Planned 500 MW utility-scale solar PV plant near Ubari in south-western Libya, capitalising on exceptional Saharan solar resources. Pre-feasibility work completed before conflict disrupted progress.",
    latitude: 26.59, longitude: 12.77,
    sourceUrl: "https://www.gecol.ly/ubari-solar",
  },

  // ── GABON (4 projects) ─────────────────────────────────────────────────────
  {
    projectName: "Grand Poubara Hydroelectric Dam",
    country: "Gabon", region: "Central Africa", technology: "Hydro",
    status: "Operational", dealSizeUsdMn: 328, capacityMw: 160,
    announcedYear: 2008,
    developer: "SEEG / Gabon Power Company",
    investors: "AfDB, Gabon Government, BNP Paribas",
    description: "160 MW run-of-river hydroelectric dam on the Ogooué River at Poubara, commissioned in 2013. The plant supplies electricity to the Transgabonais industrial corridor and the interior of Gabon.",
    latitude: -1.55, longitude: 13.75,
    sourceUrl: "https://www.afdb.org/gabon-poubara",
  },
  {
    projectName: "FE2 Onshore Oil Block (Perenco)",
    country: "Gabon", region: "Central Africa", technology: "Oil & Gas",
    status: "Operational", dealSizeUsdMn: 800, capacityMw: null,
    announcedYear: 2012,
    developer: "Perenco",
    investors: "Perenco, Gabonese Government",
    description: "Major onshore oil production block in Gabon operated by Perenco, producing over 100,000 barrels/day. Perenco is Gabon's largest oil operator, managing multiple fields across the country.",
    latitude: -1.00, longitude: 10.00,
    sourceUrl: "https://www.perenco.com/gabon",
  },
  {
    projectName: "Libreville Solar PV Plant (Ausar Energy)",
    country: "Gabon", region: "Central Africa", technology: "Solar",
    status: "Development", dealSizeUsdMn: 40, capacityMw: 25,
    announcedYear: 2021,
    developer: "Ausar Energy / SEEG",
    investors: "AfDB, IFC",
    description: "25 MW solar PV plant near Libreville, Gabon's first utility-scale solar project. Developed by Ausar Energy to reduce Gabon's reliance on thermal generation and diesel imports.",
    latitude: 0.39, longitude: 9.45,
    sourceUrl: "https://www.afdb.org/gabon-solar",
  },
  {
    projectName: "Ngoulmendjim Hydropower Project",
    country: "Gabon", region: "Central Africa", technology: "Hydro",
    status: "Development", dealSizeUsdMn: 700, capacityMw: 420,
    announcedYear: 2018,
    developer: "Gabon Power Company / Eramet",
    investors: "AfDB, Gabon Government, IFC",
    description: "420 MW hydropower project on the Abanga River, designed to supply the mining sector and expand national electricity access. One of Gabon's flagship infrastructure projects under Vision Gabon Émergent.",
    latitude: 0.25, longitude: 11.50,
    sourceUrl: "https://www.afdb.org/gabon-ngoulmendjim",
  },

  // ── EQUATORIAL GUINEA (3 projects) ─────────────────────────────────────────
  {
    projectName: "Punta Europa LNG Complex",
    country: "Equatorial Guinea", region: "Central Africa", technology: "Oil & Gas",
    status: "Operational", dealSizeUsdMn: 1400, capacityMw: null,
    announcedYear: 2004,
    developer: "Marathon Oil / EG LNG",
    investors: "Marathon Oil (60%), GEPetrol (25%), Mitsui (8.5%), Marubeni (6.5%)",
    description: "3.4 million tonnes per year LNG export facility on Bioko Island, the largest private investment in Equatorial Guinea. Operated by EG LNG, a joint venture led by Marathon Oil.",
    latitude: 3.62, longitude: 8.76,
    sourceUrl: "https://www.marathonoil.com/equatorial-guinea",
  },
  {
    projectName: "Equatorial Guinea Gas Mega Hub",
    country: "Equatorial Guinea", region: "Central Africa", technology: "Oil & Gas",
    status: "Under Construction", dealSizeUsdMn: 2000, capacityMw: null,
    announcedYear: 2019,
    developer: "GEPetrol / Noble Energy / ExxonMobil",
    investors: "GEPetrol, Noble Energy (now Chevron), ExxonMobil, GEPOG",
    description: "Natural gas aggregation and processing hub to monetise associated gas from EG's offshore fields, preventing flaring and enabling additional LNG exports. Backed by the government's Gas Mega Hub policy framework.",
    latitude: 3.75, longitude: 8.80,
    sourceUrl: "https://www.ogj.com/equatorial-guinea-gas-hub",
  },
  {
    projectName: "Sendje Ceiba Oil Field Development",
    country: "Equatorial Guinea", region: "Central Africa", technology: "Oil & Gas",
    status: "Operational", dealSizeUsdMn: 900, capacityMw: null,
    announcedYear: 2001,
    developer: "Trident Energy",
    investors: "Trident Energy, GEPetrol",
    description: "Offshore oil FPSO development in Block B offshore Equatorial Guinea, now operated by Trident Energy after acquiring assets from Hess. Produces around 35,000 barrels/day.",
    latitude: 3.20, longitude: 8.00,
    sourceUrl: "https://www.tridentenergy.co.uk/equatorial-guinea",
  },

  // ── GHANA (4 additional projects) ──────────────────────────────────────────
  {
    projectName: "Bui Hydropower Project",
    country: "Ghana", region: "West Africa", technology: "Hydro",
    status: "Operational", dealSizeUsdMn: 622, capacityMw: 400,
    announcedYear: 2005,
    developer: "Bui Power Authority",
    investors: "China Eximbank, Ghanaian Government",
    description: "400 MW dam on the Black Volta River, Ghana's second-largest hydroelectric plant. Financed by China Eximbank and constructed by Sinohydro; operates in parallel with Akosombo.",
    latitude: 8.27, longitude: -2.23,
    sourceUrl: "https://www.buipowerauthority.com",
  },
  {
    projectName: "Cenpower Kpone Independent Power Plant",
    country: "Ghana", region: "West Africa", technology: "Oil & Gas",
    status: "Operational", dealSizeUsdMn: 900, capacityMw: 340,
    announcedYear: 2011,
    developer: "Cenpower Generation Company",
    investors: "IFC, Proparco, OPIC, DEG",
    description: "340 MW gas-fired combined cycle power plant at Kpone, Greater Accra. Ghana's first large-scale IPP, financed by a consortium of DFIs including IFC and Germany's DEG.",
    latitude: 5.70, longitude: -0.06,
    sourceUrl: "https://www.ifc.org/cenpower-kpone",
  },
  {
    projectName: "Asogli Power Plant",
    country: "Ghana", region: "West Africa", technology: "Oil & Gas",
    status: "Operational", dealSizeUsdMn: 330, capacityMw: 220,
    announcedYear: 2008,
    developer: "Asogli Power (CenPower Holdings)",
    investors: "IFC, FMO, Proparco",
    description: "220 MW thermal gas plant at Takoradi, one of Ghana's key baseload generators. Expanded under an IFC-financed package to ensure electricity supply stability in the western corridor.",
    latitude: 4.90, longitude: -1.75,
    sourceUrl: "https://www.asogli.com",
  },
  {
    projectName: "Volta River Authority Solar Rooftop Programme",
    country: "Ghana", region: "West Africa", technology: "Solar",
    status: "Development", dealSizeUsdMn: 60, capacityMw: 100,
    announcedYear: 2021,
    developer: "Volta River Authority (VRA)",
    investors: "AfDB, World Bank, Ghanaian Government",
    description: "Distributed solar rooftop programme to install 100 MW of solar PV on public and commercial buildings across Ghana, reducing peak demand and diesel costs for the national grid.",
    latitude: 7.95, longitude: -1.02,
    sourceUrl: "https://www.vra.com/solar",
  },

  // ── MAURITANIA (2 additional projects) ─────────────────────────────────────
  {
    projectName: "AMAN Green Hydrogen Project",
    country: "Mauritania", region: "West Africa", technology: "Hydrogen",
    status: "Development", dealSizeUsdMn: 40000, capacityMw: 30000,
    announcedYear: 2021,
    developer: "CWP Global / Mauritanian Government",
    investors: "CWP Global, World Bank, EIB",
    description: "30 GW green hydrogen and ammonia mega-project in Mauritania, one of the world's largest planned hydrogen projects. Targets production of up to 8 million tonnes of green ammonia annually for export to Europe and Asia.",
    latitude: 20.00, longitude: -13.50,
    sourceUrl: "https://www.cwpglobal.com/aman",
  },
  {
    projectName: "Nour Solar PV Power Plant",
    country: "Mauritania", region: "West Africa", technology: "Solar",
    status: "Operational", dealSizeUsdMn: 50, capacityMw: 30,
    announcedYear: 2018,
    developer: "SOMELEC / AfDB",
    investors: "AfDB, OMVS, IsDB, EU",
    description: "30 MW solar PV plant at Boulenouar, Mauritania, one of the country's first utility-scale renewable projects. Reduces diesel generation costs and improves electricity access in Nouakchott.",
    latitude: 18.00, longitude: -16.00,
    sourceUrl: "https://www.afdb.org/mauritania-nour-solar",
  },

  // ── BOTSWANA (3 projects) ──────────────────────────────────────────────────
  {
    projectName: "Morupule B Coal Power Plant",
    country: "Botswana", region: "Southern Africa", technology: "Coal",
    status: "Operational", dealSizeUsdMn: 1100, capacityMw: 600,
    announcedYear: 2008,
    developer: "Botswana Power Corporation",
    investors: "China Eximbank, BPC, AfDB",
    description: "600 MW coal-fired power station at Palapye, Botswana's largest power plant. Financed primarily by China Eximbank and built by China National Machinery and Equipment Corporation (CMEC).",
    latitude: -22.55, longitude: 27.10,
    sourceUrl: "https://www.bpc.bw/morupule-b",
  },
  {
    projectName: "Sese Solar Power Plant",
    country: "Botswana", region: "Southern Africa", technology: "Solar",
    status: "Development", dealSizeUsdMn: 200, capacityMw: 100,
    announcedYear: 2020,
    developer: "Solarcentury / BPC",
    investors: "IFC, ABSA, Standard Bank",
    description: "Botswana's first utility-scale solar IPP at Sese near Palapye. Part of BPC's renewable energy strategy to reduce coal dependence and tap the country's world-class solar resources.",
    latitude: -22.43, longitude: 27.13,
    sourceUrl: "https://www.ifc.org/botswana-sese-solar",
  },
  {
    projectName: "BW Solar 1",
    country: "Botswana", region: "Southern Africa", technology: "Solar",
    status: "Operational", dealSizeUsdMn: 30, capacityMw: 25,
    announcedYear: 2017,
    developer: "Botswana Power Corporation",
    investors: "AfDB, BPC",
    description: "25 MW solar PV plant at Mmamabula, Botswana's first grid-connected solar project, financed by AfDB as part of a regional renewable energy push in southern Africa.",
    latitude: -23.89, longitude: 26.35,
    sourceUrl: "https://www.afdb.org/botswana-bw-solar",
  },

  // ── BURKINA FASO (4 projects) ──────────────────────────────────────────────
  {
    projectName: "Zagtouli Solar PV Plant",
    country: "Burkina Faso", region: "West Africa", technology: "Solar",
    status: "Operational", dealSizeUsdMn: 44, capacityMw: 33,
    announcedYear: 2015,
    developer: "SONABEL / AfDB",
    investors: "AfDB, EU, SEFA",
    description: "33 MW solar PV plant near Ouagadougou, the largest in West Africa at time of commissioning. Financed by the AfDB, Zagtouli has significantly reduced Burkina Faso's dependence on costly thermal generation.",
    latitude: 12.25, longitude: -1.65,
    sourceUrl: "https://www.afdb.org/burkina-faso-zagtouli",
  },
  {
    projectName: "Kodeni Thermal Power Plant Upgrade",
    country: "Burkina Faso", region: "West Africa", technology: "Oil & Gas",
    status: "Operational", dealSizeUsdMn: 80, capacityMw: 40,
    announcedYear: 2016,
    developer: "SONABEL",
    investors: "World Bank, BOAD",
    description: "Rehabilitation and expansion of the Kodeni thermal plant in Bobo-Dioulasso, Burkina Faso's second city. Supports electricity supply stability as renewable capacity is scaled up.",
    latitude: 11.15, longitude: -4.30,
    sourceUrl: "https://www.sonabel.bf/kodeni",
  },
  {
    projectName: "Pa Solar Power Plant",
    country: "Burkina Faso", region: "West Africa", technology: "Solar",
    status: "Development", dealSizeUsdMn: 35, capacityMw: 22,
    announcedYear: 2019,
    developer: "SONABEL / Urbasolar",
    investors: "EU, AFD, SEFA",
    description: "22 MW solar project at Pa in southern Burkina Faso, co-financed by the EU and AFD. Part of a multi-site solar programme to reduce load-shedding and improve rural electricity access.",
    latitude: 11.54, longitude: -3.04,
    sourceUrl: "https://www.afd.fr/burkina-faso-pa-solar",
  },
  {
    projectName: "Pâ-Kaya Solar PV Park",
    country: "Burkina Faso", region: "West Africa", technology: "Solar",
    status: "Development", dealSizeUsdMn: 50, capacityMw: 30,
    announcedYear: 2021,
    developer: "SONABEL / Eiffage",
    investors: "AfDB, SEFA, AFD",
    description: "30 MW solar plant at Kaya in north-central Burkina Faso, developed by Eiffage under a build-operate-transfer agreement. Forms part of the AfDB-backed SREP programme for the Sahel region.",
    latitude: 12.96, longitude: -1.09,
    sourceUrl: "https://www.afdb.org/burkina-faso-kaya-solar",
  },

  // ── WORLD BANK API additions (structured data supplement) ──────────────────
  {
    projectName: "Niger Rural Electrification Solar Mini-Grid Programme",
    country: "Niger", region: "West Africa", technology: "Solar",
    status: "Development", dealSizeUsdMn: 150, capacityMw: 40,
    announcedYear: 2021,
    developer: "Ministry of Energy / NIGELEC",
    investors: "World Bank, IDA, EU",
    description: "World Bank IDA-financed programme to deploy 40 MW of solar mini-grids across 400+ villages in Niger, serving 300,000 people. Part of the Sahel renewable energy initiative.",
    latitude: 13.51, longitude: 2.12,
    sourceUrl: "https://projects.worldbank.org/niger-rural-electrification",
  },
  {
    projectName: "Sudan Power Sector Rehabilitation",
    country: "Sudan", region: "North Africa", technology: "Grid Expansion",
    status: "Development", dealSizeUsdMn: 230, capacityMw: null,
    announcedYear: 2022,
    developer: "Ministry of Energy / SEDC",
    investors: "World Bank, IsDB, AfDB",
    description: "Rehabilitation of Sudan's deteriorating electricity transmission and distribution infrastructure, targeting a 20% reduction in losses and improved supply reliability for 2 million households.",
    latitude: 15.55, longitude: 32.53,
    sourceUrl: "https://projects.worldbank.org/sudan-power-sector",
  },
  {
    projectName: "Djibouti Geothermal Power Project",
    country: "Djibouti", region: "East Africa", technology: "Bioenergy",
    status: "Development", dealSizeUsdMn: 450, capacityMw: 50,
    announcedYear: 2018,
    developer: "Office Djiboutien de Développement de l'Énergie Géothermique",
    investors: "World Bank, EIB, AfDB, KfW",
    description: "50 MW geothermal power plant at the Fiale Caldera in Djibouti's volcanic zone. Aims to replace expensive diesel generation and enable electricity exports to Ethiopia and Somalia.",
    latitude: 11.51, longitude: 42.70,
    sourceUrl: "https://www.afdb.org/djibouti-geothermal",
  },
  {
    projectName: "Congo Republic Imboulou Hydropower Plant",
    country: "Congo Republic", region: "Central Africa", technology: "Hydro",
    status: "Operational", dealSizeUsdMn: 400, capacityMw: 120,
    announcedYear: 2003,
    developer: "SNE / China National Water Resources",
    investors: "China Eximbank, Congo Government",
    description: "120 MW hydroelectric plant on the Léfini River in the Republic of Congo, built by Chinese contractors and financed by China Eximbank. Supplies Brazzaville and reduces dependence on imported power.",
    latitude: -2.80, longitude: 15.80,
    sourceUrl: "https://www.afdb.org/congo-imboulou",
  },
  {
    projectName: "Togo Contour Global Kekeli Efficient Power",
    country: "Togo", region: "West Africa", technology: "Oil & Gas",
    status: "Operational", dealSizeUsdMn: 230, capacityMw: 100,
    announcedYear: 2015,
    developer: "ContourGlobal",
    investors: "IFC, DEG, Proparco, FMO",
    description: "100 MW dual-fuel power plant at Lomé Port providing electricity to Togo and Benin. Financed by a DFI consortium led by IFC, it provides stable baseload power to the CEB regional grid.",
    latitude: 6.13, longitude: 1.22,
    sourceUrl: "https://www.contourglobal.com/togo-kekeli",
  },
  {
    projectName: "Benin Maria Gléta II Power Plant",
    country: "Benin", region: "West Africa", technology: "Oil & Gas",
    status: "Operational", dealSizeUsdMn: 250, capacityMw: 127,
    announcedYear: 2017,
    developer: "SBEE / Aggreko",
    investors: "AfDB, World Bank, ECOWAS Bank",
    description: "127 MW thermal power expansion at Maria Gléta near Cotonou, addressing Benin's chronic electricity deficit. Financed by AfDB and World Bank as part of regional electricity market integration.",
    latitude: 6.42, longitude: 2.47,
    sourceUrl: "https://www.afdb.org/benin-maria-gleta",
  },
  {
    projectName: "Zimbabwe Hwange Thermal Power Station Expansion",
    country: "Zimbabwe", region: "Southern Africa", technology: "Coal",
    status: "Under Construction", dealSizeUsdMn: 1500, capacityMw: 600,
    announcedYear: 2015,
    developer: "ZESA / Sinohydro",
    investors: "China Eximbank, ZESA",
    description: "600 MW expansion of the Hwange coal power station, Zimbabwe's main electricity generating facility. Financed by China Eximbank under a US$1.5B government-to-government agreement.",
    latitude: -18.36, longitude: 26.49,
    sourceUrl: "https://www.zesa.co.zw/hwange-expansion",
  },
  {
    projectName: "Sierra Leone Bumbuna Phase II Hydropower",
    country: "Sierra Leone", region: "West Africa", technology: "Hydro",
    status: "Development", dealSizeUsdMn: 500, capacityMw: 143,
    announcedYear: 2016,
    developer: "Joule Africa / NPA",
    investors: "AfDB, IFC, OPEC Fund",
    description: "143 MW expansion of the Bumbuna hydropower scheme on the Seli River, Sierra Leone. Financed by AfDB and IFC, the expansion will triple the country's installed hydro capacity.",
    latitude: 9.03, longitude: -11.77,
    sourceUrl: "https://www.afdb.org/sierra-leone-bumbuna-ii",
  },
  {
    projectName: "Somalia Mogadishu Solar Mini-Grid Network",
    country: "Somalia", region: "East Africa", technology: "Solar",
    status: "Development", dealSizeUsdMn: 80, capacityMw: 30,
    announcedYear: 2022,
    developer: "Ministry of Energy / SOMA OIL & GAS",
    investors: "World Bank, IsDB, USAID",
    description: "30 MW distributed solar mini-grid network for Mogadishu and secondary cities, funded by the World Bank and IsDB to improve electricity access in post-conflict Somalia.",
    latitude: 2.05, longitude: 45.34,
    sourceUrl: "https://projects.worldbank.org/somalia-solar",
  },
  {
    projectName: "Malawi Tedzani Hydropower Rehabilitation",
    country: "Malawi", region: "East Africa", technology: "Hydro",
    status: "Operational", dealSizeUsdMn: 60, capacityMw: 92,
    announcedYear: 2016,
    developer: "Electricity Generation Company (EGENCO)",
    investors: "AfDB, NDF, EU",
    description: "Rehabilitation of the Tedzani hydropower stations on the Shire River, restoring 92 MW of capacity lost to drought-induced low water levels and mechanical failures.",
    latitude: -15.77, longitude: 35.20,
    sourceUrl: "https://www.afdb.org/malawi-tedzani",
  },
  {
    projectName: "Cape Verde Cabeólica Wind Farm",
    country: "Cape Verde", region: "West Africa", technology: "Wind",
    status: "Operational", dealSizeUsdMn: 77, capacityMw: 25.5,
    announcedYear: 2011,
    developer: "Cabeólica S.A.",
    investors: "IFC, AfDB, EDP Renováveis, InfraVia",
    description: "25.5 MW wind farm across four of Cape Verde's islands, providing 30% of the archipelago's electricity needs. A landmark African renewable energy IPP financed by IFC and AfDB.",
    latitude: 15.12, longitude: -23.61,
    sourceUrl: "https://www.cabeolica.com",
  },
  {
    projectName: "Madagascar Ambatolampy Hydropower",
    country: "Madagascar", region: "East Africa", technology: "Hydro",
    status: "Development", dealSizeUsdMn: 150, capacityMw: 80,
    announcedYear: 2020,
    developer: "JIRAMA",
    investors: "AfDB, World Bank, EIB",
    description: "80 MW run-of-river hydro project at Ambatolampy to serve the Antananarivo capital region, addressing Madagascar's severe electricity access deficit. Financed by AfDB and World Bank.",
    latitude: -19.38, longitude: 47.43,
    sourceUrl: "https://www.afdb.org/madagascar-ambatolampy",
  },
  {
    projectName: "Mauritius Plaines des Roches Solar Farm",
    country: "Mauritius", region: "East Africa", technology: "Solar",
    status: "Operational", dealSizeUsdMn: 40, capacityMw: 17,
    announcedYear: 2018,
    developer: "Central Electricity Board (CEB) / Engie",
    investors: "Engie, AFD, EIB",
    description: "Mauritius's largest solar PV plant at Plaines des Roches, operated by a CEB-Engie partnership. Generates 27 GWh annually and supports the national goal of 35% renewable energy by 2025.",
    latitude: -20.06, longitude: 57.67,
    sourceUrl: "https://www.ceb.mu/plaines-des-roches",
  },
];
