import { db, projectsTable } from "@workspace/db";
import { sql } from "drizzle-orm";

const projects = [
  // Solar
  { projectName: "Benban Solar Park", country: "Egypt", region: "North Africa", technology: "Solar", dealSizeUsdMn: 2000, investors: "Scatec, JICA, IFC, EBRD", status: "Operational", latitude: 24.48, longitude: 32.93, capacityMw: 1650, announcedYear: 2017, closedYear: 2019, description: "One of Africa's largest solar parks located in Aswan Governorate.", sourceUrl: "https://www.scatec.com/project/benban/", newsUrl: "https://www.bloomberg.com/news/articles/2018-03-13/desert-sun-to-power-upper-egypt-with-2-8-billion-solar-park" },
  { projectName: "Redstone Solar Thermal Power", country: "South Africa", region: "Southern Africa", technology: "Solar", dealSizeUsdMn: 920, investors: "ACWA Power, IDC, DBSA", status: "Under Construction", latitude: -29.05, longitude: 22.18, capacityMw: 100, announcedYear: 2019, closedYear: 2021, description: "CSP plant with molten salt storage in Northern Cape.", sourceUrl: "https://acwapower.com/en/projects/redstone-csp-ipp/", newsUrl: null },
  { projectName: "Nzema Solar Project", country: "Ghana", region: "West Africa", technology: "Solar", dealSizeUsdMn: 400, investors: "Blue Energy, IFC", status: "Development", latitude: 4.88, longitude: -2.3, capacityMw: 155, announcedYear: 2012, closedYear: null, description: "One of West Africa's largest solar projects.", sourceUrl: "https://ppi.worldbank.org/en/snapshots/project/nzema-solar-pv-7387", newsUrl: null },
  { projectName: "Ouarzazate Solar Complex (NOOR)", country: "Morocco", region: "North Africa", technology: "Solar", dealSizeUsdMn: 2400, investors: "World Bank, AFDB, EIB, KfW, CIF", status: "Operational", latitude: 30.9, longitude: -6.9, capacityMw: 580, announcedYear: 2012, closedYear: 2016, description: "NOOR I, II, III CSP and solar PV complex south of Ouarzazate.", sourceUrl: "https://www.masen.ma/en/projects/noor-ouarzazate-i", newsUrl: "https://www.esi-africa.com/features-analysis/morocco-pushing-renewables-boundary-noor-midelt-projects/" },
  { projectName: "Xina Solar One", country: "South Africa", region: "Southern Africa", technology: "Solar", dealSizeUsdMn: 530, investors: "IDC, DBSA, Abengoa, IFC", status: "Operational", latitude: -28.73, longitude: 19.73, capacityMw: 100, announcedYear: 2014, closedYear: 2017, description: "Parabolic trough CSP with thermal storage in Northern Cape.", sourceUrl: "https://disclosures.ifc.org/project-detail/SII/34051/xina-solar-one-pty-ltd", newsUrl: "https://www.esi-africa.com/renewable-energy/xina-solar-one-first-energy-sale-windows/" },
  { projectName: "Lake Turkana Wind Power", country: "Kenya", region: "East Africa", technology: "Wind", dealSizeUsdMn: 694, investors: "LTWP Consortium, KfW, AFDB, EIB", status: "Operational", latitude: 2.72, longitude: 36.37, capacityMw: 310, announcedYear: 2011, closedYear: 2017, description: "Africa's largest wind farm located on the shores of Lake Turkana.", sourceUrl: "https://ltwp.co.ke/", newsUrl: null },
  { projectName: "Tarfaya Wind Farm", country: "Morocco", region: "North Africa", technology: "Wind", dealSizeUsdMn: 850, investors: "Nareva, GDF Suez, IFC", status: "Operational", latitude: 27.94, longitude: -12.93, capacityMw: 300, announcedYear: 2012, closedYear: 2014, description: "Africa's largest onshore wind farm at time of completion.", sourceUrl: "https://www.nareva.ma/en/project/wind-farm-tarfaya", newsUrl: "https://www.esi-africa.com/top-stories/moroccos-tarfaya-wind-farm-generates-power/" },
  { projectName: "Adama Wind Farm Phase II", country: "Ethiopia", region: "East Africa", technology: "Wind", dealSizeUsdMn: 172, investors: "Chinese Exim Bank, Ethiopian Electric Power", status: "Operational", latitude: 8.54, longitude: 39.27, capacityMw: 153, announcedYear: 2011, closedYear: 2015, description: "Second phase of the Adama wind farm near Addis Ababa.", sourceUrl: "https://www.power-technology.com/data-insights/power-plant-profile-adama-ii-wind-farm-ethiopia/", newsUrl: "https://www.esi-africa.com/top-stories/153mw-adama-wind-farm-grows-ethiopias-renewable-energy-plan/" },
  { projectName: "Loeriesfontein 2 Wind Farm", country: "South Africa", region: "Southern Africa", technology: "Wind", dealSizeUsdMn: 260, investors: "ENGIE, Mainstream Renewable, DBSA", status: "Operational", latitude: -30.97, longitude: 19.44, capacityMw: 140, announcedYear: 2013, closedYear: 2017, description: "Wind farm in the Northern Cape under REIPPPP.", sourceUrl: "https://loeriesfonteinwind.co.za/", newsUrl: "https://www.esi-africa.com/industry-sectors/business-and-markets/miga-approves-guarantees-for-three-wind-farms-in-south-africa/" },
  { projectName: "Bujagali Hydropower", country: "Uganda", region: "East Africa", technology: "Hydro", dealSizeUsdMn: 900, investors: "IFC, World Bank, AFDB, Aga Khan Fund", status: "Operational", latitude: 0.45, longitude: 33.14, capacityMw: 250, announcedYear: 2007, closedYear: 2012, description: "Run-of-river hydro project on the Nile.", sourceUrl: "https://www.bujagali-energy.com/", newsUrl: "https://documents.worldbank.org/en/publication/documents-reports/documentdetail/307371468760804260/uganda-bujagali-hydropower-project" },
  { projectName: "Karuma Hydropower Plant", country: "Uganda", region: "East Africa", technology: "Hydro", dealSizeUsdMn: 1700, investors: "Chinese Exim Bank, Uganda Electricity Generation", status: "Operational", latitude: 2.25, longitude: 32.23, capacityMw: 600, announcedYear: 2013, closedYear: 2022, description: "Uganda's largest hydropower plant on the Victoria Nile.", sourceUrl: "https://uegcl.com/karuma-hydropower-station/", newsUrl: "https://www.theafricareport.com/258195/uganda-is-servicing-a-1-4bn-chinese-loan-for-an-incomplete-hydropower-dam/" },
  { projectName: "Ruzizi III Hydropower", country: "DRC", region: "Central Africa", technology: "Hydro", dealSizeUsdMn: 650, investors: "AFDB, EIB, KfW, IFC", status: "Development", latitude: -2.7, longitude: 28.87, capacityMw: 147, announcedYear: 2015, closedYear: null, description: "Regional hydro project shared by DRC, Burundi and Rwanda.", sourceUrl: "https://www.afdb.org/en/news-and-events/afdb-approves-ruzizi-iii-hydropower-plant-project-bringing-green-energy-to-burundi-drc-and-rwanda-15275", newsUrl: "https://www.afdb.org/en/news-and-events/afdb-approves-regional-hydropower-ppp-to-increase-electricity-supply-and-integration-in-burundi-drc-rwanda-15255/" },
  { projectName: "Nachtigal Hydro Power", country: "Cameroon", region: "Central Africa", technology: "Hydro", dealSizeUsdMn: 1200, investors: "IFC, AFDB, EIB, Proparco, Total Energies", status: "Under Construction", latitude: 4.37, longitude: 11.62, capacityMw: 420, announcedYear: 2018, closedYear: 2021, description: "Run-of-river hydro on the Sanaga River.", sourceUrl: "https://nhpc.cm/", newsUrl: "https://www.ifc.org/en/stories/2010/nachtigal-cameroon-hydropower-plant-clean-power" },
  { projectName: "Menengai Geothermal", country: "Kenya", region: "East Africa", technology: "Geothermal", dealSizeUsdMn: 1300, investors: "AFDB, KfW, Japan, World Bank", status: "Under Construction", latitude: -0.2, longitude: 36.07, capacityMw: 400, announcedYear: 2013, closedYear: null, description: "Geothermal development in the Kenyan Rift Valley.", sourceUrl: "https://www.gdc.co.ke/menengai/", newsUrl: "https://www.afdb.org/en/success-stories/kenyas-menengai-geothermal-project-power-half-million-homes-clean-energy-74832" },
  { projectName: "Olkaria IV Geothermal", country: "Kenya", region: "East Africa", technology: "Geothermal", dealSizeUsdMn: 350, investors: "World Bank, Japan JICA, KenGen", status: "Operational", latitude: -0.9, longitude: 36.29, capacityMw: 140, announcedYear: 2010, closedYear: 2014, description: "Expansion of the Olkaria geothermal complex.", sourceUrl: "https://www.kengen.co.ke/", newsUrl: null },
  { projectName: "Corbetti Geothermal", country: "Ethiopia", region: "East Africa", technology: "Geothermal", dealSizeUsdMn: 1000, investors: "Reykjavik Geothermal, IFC, DFIs", status: "Development", latitude: 7.18, longitude: 38.42, capacityMw: 500, announcedYear: 2016, closedYear: null, description: "Large-scale geothermal development in the East African Rift.", sourceUrl: "https://rg.is/project/corbetti/", newsUrl: "https://www.esi-africa.com/industry-sectors/generation/corbetti-geothermal-project-to-add-20mw-to-ethiopias-grid/" },
  { projectName: "Dangote Refinery", country: "Nigeria", region: "West Africa", technology: "Oil & Gas", dealSizeUsdMn: 19000, investors: "Dangote Group, NNPC, Afreximbank", status: "Operational", latitude: 6.39, longitude: 3.38, capacityMw: null, announcedYear: 2013, closedYear: 2023, description: "Africa's largest oil refinery located near Lagos.", sourceUrl: "https://www.dangote.com/our-companies/dangote-petroleum-refinery/", newsUrl: "https://www.bloomberg.com/news/articles/2023-05-22/seven-years-late-nigeria-s-mega-oil-refinery-opens-with-a-whimper" },
  { projectName: "Coral FLNG", country: "Mozambique", region: "East Africa", technology: "Oil & Gas", dealSizeUsdMn: 7000, investors: "ENI, ExxonMobil, CNPC, GALP, KOGAS, Mozambique State", status: "Operational", latitude: -12.23, longitude: 41.01, capacityMw: null, announcedYear: 2016, closedYear: 2022, description: "Africa's first floating LNG facility offshore Mozambique.", sourceUrl: "https://www.eni.com/en-IT/actions/global-activities/mozambique/coral-south.html", newsUrl: "https://www.bloomberg.com/news/articles/2022-08-02/eni-plans-second-lng-platform-off-mozambique-as-europe-seeks-gas" },
  { projectName: "SNE Deepwater Oil Field", country: "Senegal", region: "West Africa", technology: "Oil & Gas", dealSizeUsdMn: 5000, investors: "Woodside, BP, Cairn Energy, Petrosen", status: "Under Construction", latitude: 12.4, longitude: -17.5, capacityMw: null, announcedYear: 2016, closedYear: null, description: "Offshore oil field development - Sangomar Phase 1.", sourceUrl: "https://www.woodside.com/what-we-do/operations/sangomar", newsUrl: null },
  { projectName: "Greater Tortue Ahmeyim LNG", country: "Mauritania", region: "West Africa", technology: "Oil & Gas", dealSizeUsdMn: 4700, investors: "BP, Kosmos Energy, SMHPM, Petrosen", status: "Under Construction", latitude: 20.3, longitude: -17.08, capacityMw: null, announcedYear: 2018, closedYear: 2020, description: "Cross-border LNG project between Mauritania and Senegal.", sourceUrl: "https://www.kosmosenergy.com/greater-tortue/", newsUrl: "https://www.bp.com/en/global/corporate/news-and-insights/press-releases/bp-flows-first-gas-at-greater-tortue-ahmeyim-lng-project.html" },
  { projectName: "Kipeto Wind Energy", country: "Kenya", region: "East Africa", technology: "Wind", dealSizeUsdMn: 150, investors: "Craftskills Wind Energy, IFC, DEG, FMO", status: "Operational", latitude: -2.0, longitude: 36.5, capacityMw: 100, announcedYear: 2015, closedYear: 2021, description: "Wind farm in Kajiado County.", sourceUrl: "https://www.meridiam.com/assets/kipeto-wind-farm-2/", newsUrl: "https://www.esi-africa.com/renewable-energy/100mw-kipeto-wind-farm-connects-to-kenyas-power-grid/" },
  { projectName: "Scaling Solar Zambia", country: "Zambia", region: "Southern Africa", technology: "Solar", dealSizeUsdMn: 300, investors: "IFC, Scaling Solar, Government of Zambia", status: "Operational", latitude: -15.42, longitude: 28.28, capacityMw: 100, announcedYear: 2017, closedYear: 2019, description: "World Bank Scaling Solar initiative first project.", sourceUrl: "https://www.scalingsolar.org/active-engagements/zambia/", newsUrl: "https://www.worldbank.org/en/news/feature/2019/05/14/unlocking-low-cost-large-scale-solar-power-in-zambia" },
  { projectName: "Segou Solar Project", country: "Mali", region: "West Africa", technology: "Solar", dealSizeUsdMn: 45, investors: "BNEE, EDM, AFDB", status: "Development", latitude: 13.45, longitude: -6.27, capacityMw: 33, announcedYear: 2018, closedYear: null, description: "Solar PV project in Segou region.", sourceUrl: "https://www.afdb.org/en/news-and-events/mali-to-receive-us-25-million-concessional-loan-to-build-utility-scale-solar-photovoltaic-plant-and-transform-the-west-african-energy-market-16767", newsUrl: "https://www.afdb.org/en/news-and-events/mali-to-receive-us-25-million-concessional-loan-to-build-utility-scale-solar-photovoltaic-plant-and-transform-the-west-african-energy-market-16767" },
  { projectName: "Cabeólica Wind Farm", country: "Cape Verde", region: "West Africa", technology: "Wind", dealSizeUsdMn: 76, investors: "InfraCo Africa, IFC, FMO, Electra", status: "Operational", latitude: 14.93, longitude: -23.51, capacityMw: 30, announcedYear: 2010, closedYear: 2012, description: "Wind farms on four Cape Verde islands.", sourceUrl: "https://cabeolica.com/en/a-nossa-historia/", newsUrl: null },
  { projectName: "Ashegoda Wind Farm", country: "Ethiopia", region: "East Africa", technology: "Wind", dealSizeUsdMn: 215, investors: "Vergnet, Proparco, Ethiopian Government", status: "Operational", latitude: 13.55, longitude: 39.54, capacityMw: 120, announcedYear: 2009, closedYear: 2013, description: "Wind farm in Tigray region of Ethiopia.", sourceUrl: "https://www.afd.fr/en/carte-des-projets/ethiopias-first-wind-farm-mekele", newsUrl: "https://www.esi-africa.com/news/ethiopia-wind-farm-starts-to-feed-energy-into-national-grid/" },
  { projectName: "Symbion Dar es Salaam Gas Power", country: "Tanzania", region: "East Africa", technology: "Oil & Gas", dealSizeUsdMn: 250, investors: "Symbion Power, OPIC, DEG", status: "Operational", latitude: -6.79, longitude: 39.22, capacityMw: 112, announcedYear: 2014, closedYear: 2016, description: "Gas-fired power plant using Tanzanian natural gas.", sourceUrl: "https://www.symbion-power.com/tanzania/", newsUrl: "https://www.esi-africa.com/features-analysis/interview-with-paul-hinks-ceo-symbion-power/" },
  { projectName: "Azito Phase 3 Gas Power", country: "Côte d'Ivoire", region: "West Africa", technology: "Oil & Gas", dealSizeUsdMn: 300, investors: "Globeleq, IFC, AfDB, OPIC", status: "Operational", latitude: 5.32, longitude: -4.03, capacityMw: 253, announcedYear: 2013, closedYear: 2016, description: "Combined-cycle gas turbine expansion project in Abidjan.", sourceUrl: "https://globeleq.com/power-plants/azito/", newsUrl: "https://globeleq.com/ifc-invests-in-and-arranges-financing-package-for-the-azito-power-plant-expansion/" },
  { projectName: "Lekela Loeriesfontein Wind", country: "South Africa", region: "Southern Africa", technology: "Wind", dealSizeUsdMn: 190, investors: "Lekela Power, Mainstream Renewable", status: "Operational", latitude: -30.95, longitude: 19.41, capacityMw: 140, announcedYear: 2015, closedYear: 2017, description: "Wind farm in the Northern Cape province.", sourceUrl: "https://loeriesfonteinwind.co.za/", newsUrl: "https://lekela.com/projects/south-africa-loeriesfontein-2/" },
  { projectName: "BBOXX Solar Home Systems", country: "Rwanda", region: "East Africa", technology: "Solar", dealSizeUsdMn: 50, investors: "BBOXX, IFC, Mitsubishi Corporation", status: "Active", latitude: -1.94, longitude: 29.87, capacityMw: null, announcedYear: 2018, closedYear: 2019, description: "Off-grid solar home system rollout across Rwanda.", sourceUrl: "https://www.bboxx.com/countries/rwanda/", newsUrl: "https://www.pv-magazine.com/2019/05/22/bboxx-secures-8-million-loan-to-boost-rwanda-operations/" },
  { projectName: "Bokpoort CSP Plant", country: "South Africa", region: "Southern Africa", technology: "Solar", dealSizeUsdMn: 620, investors: "ACWA Power, IDC, DBSA", status: "Operational", latitude: -28.73, longitude: 21.97, capacityMw: 55, announcedYear: 2013, closedYear: 2016, description: "CSP plant with 9.3-hour thermal storage.", sourceUrl: "https://acwapower.com/en/projects/bokpoort-csp-ipp/", newsUrl: "https://www.esi-africa.com/solar/csp-plant-breaks-african-record-for-around-the-clock-operation/" },
  { projectName: "Kribi LNG Terminal", country: "Cameroon", region: "Central Africa", technology: "Oil & Gas", dealSizeUsdMn: 550, investors: "Golar LNG, NewAge, Perenco, SNH Cameroon", status: "Operational", latitude: 2.94, longitude: 9.91, capacityMw: null, announcedYear: 2016, closedYear: 2018, description: "Floating storage and regasification unit at Kribi.", sourceUrl: "https://www.snh.cm/index.php/en/gas-up/export-of-natural-gas", newsUrl: null },
  { projectName: "Koysha Hydropower", country: "Ethiopia", region: "East Africa", technology: "Hydro", dealSizeUsdMn: 1800, investors: "Chinese Exim Bank, Ethiopian Electric Power", status: "Under Construction", latitude: 6.93, longitude: 37.55, capacityMw: 2160, announcedYear: 2016, closedYear: null, description: "Major hydro project on the Omo River.", sourceUrl: "https://www.webuildgroup.com/en/projects/dams-hydroelectric-plants/koysha-hydroelectric-project/", newsUrl: "https://ethiopianmonitor.com/2023/12/22/pm-koysha-hydropower-project-making-progress/" },
  { projectName: "ZESCO Kafue Gorge Lower", country: "Zambia", region: "Southern Africa", technology: "Hydro", dealSizeUsdMn: 2000, investors: "Chinese Exim Bank, ZESCO, Government of Zambia", status: "Operational", latitude: -15.82, longitude: 28.43, capacityMw: 750, announcedYear: 2014, closedYear: 2021, description: "Expansion of the Kafue Gorge hydropower scheme.", sourceUrl: "https://www.power-technology.com/marketdata/power-plant-profile-kafue-gorge-lower-zambia/", newsUrl: "https://documents.worldbank.org/en/publication/documents-reports/documentdetail/542071501134244317/main-report" },
  { projectName: "Mocuba Solar Project", country: "Mozambique", region: "East Africa", technology: "Solar", dealSizeUsdMn: 70, investors: "Voltalia, IFC, EDM Mozambique", status: "Operational", latitude: -16.84, longitude: 36.99, capacityMw: 40, announcedYear: 2017, closedYear: 2019, description: "Scaling Solar initiative in Zambezia Province.", sourceUrl: "https://disclosures.ifc.org/project-detail/SII/36787/mocuba-solar", newsUrl: "https://www.esi-africa.com/renewable-energy/mozambique-inaugurates-40mw-solar-plant/" },
  { projectName: "Nachtigal Phase II Solar", country: "Cameroon", region: "Central Africa", technology: "Solar", dealSizeUsdMn: 200, investors: "IFC, AFDB, Proparco, NHPC", status: "Development", latitude: 4.2, longitude: 11.6, capacityMw: 200, announcedYear: 2022, closedYear: null, description: "Planned solar PV complementing the Nachtigal hydro facility.", sourceUrl: "https://projectsportal.afdb.org/dataportal/VProject/show/P-CM-F00-006", newsUrl: null },
  { projectName: "Serengeti Energy Mini-Grids", country: "Tanzania", region: "East Africa", technology: "Solar", dealSizeUsdMn: 15, investors: "Serengeti Energy, AFDB, SEFA", status: "Active", latitude: -5.0, longitude: 35.0, capacityMw: 5, announcedYear: 2019, closedYear: 2021, description: "Mini-grid solar deployments in rural Tanzania.", sourceUrl: "https://greenminigrid.afdb.org/about-us", newsUrl: null },
  { projectName: "Photon Energy Nigeria Solar", country: "Nigeria", region: "West Africa", technology: "Solar", dealSizeUsdMn: 120, investors: "Photon Energy, DEG, FMO", status: "Development", latitude: 9.05, longitude: 7.47, capacityMw: 50, announcedYear: 2020, closedYear: null, description: "Utility-scale solar PV project in Nigeria.", sourceUrl: "https://www.photonenergy.com/", newsUrl: null },
  { projectName: "KEPCO Rabai Power", country: "Kenya", region: "East Africa", technology: "Oil & Gas", dealSizeUsdMn: 180, investors: "KEPCO, IFC, DEG, Proparco", status: "Operational", latitude: -3.77, longitude: 39.52, capacityMw: 90, announcedYear: 2009, closedYear: 2012, description: "Oil-fired IPP near Mombasa.", sourceUrl: "https://rabaipower.com/", newsUrl: null },
  { projectName: "Parc Eolien de Taiba Ndiaye", country: "Senegal", region: "West Africa", technology: "Wind", dealSizeUsdMn: 200, investors: "Lekela Power, CDC, IFC, FMO", status: "Operational", latitude: 15.1, longitude: -16.55, capacityMw: 158, announcedYear: 2017, closedYear: 2021, description: "West Africa's largest wind farm.", sourceUrl: "https://lekela.com/projects/senegal-taiba-ndiaye/", newsUrl: "https://lekela.com/projects/senegal-taiba-ndiaye/" },
  { projectName: "Sahanivotry Hydropower", country: "Madagascar", region: "Southern Africa", technology: "Hydro", dealSizeUsdMn: 110, investors: "EDF, BNI Madagascar, JICA", status: "Operational", latitude: -19.8, longitude: 46.85, capacityMw: 15, announcedYear: 2012, closedYear: 2015, description: "Hydropower project in central Madagascar.", sourceUrl: "https://www.berkeley-energy.com/project/sahanivotry-hydro-madagascar/", newsUrl: null },
  { projectName: "Gigawatt Global Rwanda Solar", country: "Rwanda", region: "East Africa", technology: "Solar", dealSizeUsdMn: 24, investors: "Gigawatt Global, IFC, Norfund, FMO", status: "Operational", latitude: -2.5, longitude: 30.18, capacityMw: 8.5, announcedYear: 2014, closedYear: 2015, description: "First utility-scale solar plant in Rwanda.", sourceUrl: "https://gigawattglobal.com/", newsUrl: "https://www.pv-magazine.com/2014/02/18/global-consortium-collaborates-on-8-5-mw-rwanda-solar-plant_100014270/" },
  { projectName: "M-KOPA Solar Kenya", country: "Kenya", region: "East Africa", technology: "Solar", dealSizeUsdMn: 55, investors: "M-KOPA, CDC Group, Lightrock, IFC", status: "Active", latitude: -1.29, longitude: 36.82, capacityMw: null, announcedYear: 2012, closedYear: 2013, description: "Pay-as-you-go solar home systems across East Africa.", sourceUrl: "https://www.m-kopa.com/", newsUrl: "https://www.ifc.org/en/pressroom/2023/ifc-sustainability-linked-loan-to-m-kopa-to-boost-access-to-financial-services-in-eastern-africa" },
  { projectName: "Kipushi Zinc Mine Power", country: "DRC", region: "Central Africa", technology: "Solar", dealSizeUsdMn: 30, investors: "Ivanhoe Mines, Zincor", status: "Development", latitude: -11.77, longitude: 27.26, capacityMw: 20, announcedYear: 2021, closedYear: null, description: "Behind-the-meter solar for the Kipushi mine.", sourceUrl: "https://www.ivanhoemines.com/what-we-do/operations-projects/kipushi-development-project/", newsUrl: null },
  { projectName: "Africa GreenTec Mali Solar", country: "Mali", region: "West Africa", technology: "Solar", dealSizeUsdMn: 8, investors: "Africa GreenTec, DEG, ImpactNexus", status: "Active", latitude: 12.65, longitude: -8.0, capacityMw: 2, announcedYear: 2018, closedYear: 2019, description: "Community solar mini-grids in rural Mali.", sourceUrl: "https://www.africagreentec.com/en/where-we-work/mali/", newsUrl: "https://www.afrik21.africa/en/mali-africa-green-tec-installs-containerised-solar-mini-grid-in-dalakana/" },
  { projectName: "SolarAfrica Malawi", country: "Malawi", region: "Southern Africa", technology: "Solar", dealSizeUsdMn: 22, investors: "SolarAfrica, Norfund, REDF", status: "Operational", latitude: -13.97, longitude: 33.78, capacityMw: 10, announcedYear: 2020, closedYear: 2022, description: "C&I solar installations across Malawi.", sourceUrl: "https://solarafrica.com/", newsUrl: null },
  { projectName: "Singrobo Hydropower", country: "Côte d'Ivoire", region: "West Africa", technology: "Hydro", dealSizeUsdMn: 270, investors: "Themis Energy, IFC, AFDB, Proparco", status: "Under Construction", latitude: 6.44, longitude: -5.03, capacityMw: 44, announcedYear: 2018, closedYear: 2020, description: "Run-of-river hydro on the Bandama River.", sourceUrl: "https://www.afdb.org/en/news-and-events/press-releases/cote-divoire-african-development-bank-africa-finance-corporation-german-investment-corporation-and-emerging-africa-infrastructure-fund-reach-financial-close-eu1743-million-singrobo-hydropower-plant-57526", newsUrl: null },
  { projectName: "Scaling Solar Senegal", country: "Senegal", region: "West Africa", technology: "Solar", dealSizeUsdMn: 180, investors: "IFC Scaling Solar, Engie, Meridiam, Senelec", status: "Operational", latitude: 14.74, longitude: -17.43, capacityMw: 60, announcedYear: 2016, closedYear: 2019, description: "Two Scaling Solar plants in Senegal.", sourceUrl: "https://www.scalingsolar.org/active-engagements/senegal/", newsUrl: "https://www.pv-magazine.com/2019/07/22/engie-secures-financing-for-60-mw-of-solar-in-senegal/" },
  { projectName: "Sembcorp Sirajpur Solar", country: "South Africa", region: "Southern Africa", technology: "Solar", dealSizeUsdMn: 180, investors: "Sembcorp, IDC, DBSA", status: "Operational", latitude: -27.14, longitude: 25.32, capacityMw: 75, announcedYear: 2014, closedYear: 2016, description: "Solar PV under REIPPPP Round 3.", sourceUrl: "https://www.ipp-projects.co.za/ProjectDatabase/", newsUrl: null },
  { projectName: "Integrated Power Company Gas", country: "Nigeria", region: "West Africa", technology: "Oil & Gas", dealSizeUsdMn: 4800, investors: "IPC, Dangote, NNPC, Shell, Total", status: "Development", latitude: 5.55, longitude: 5.78, capacityMw: 3000, announcedYear: 2021, closedYear: null, description: "Large-scale gas-to-power project in Nigeria's Niger Delta.", sourceUrl: "https://www.power-technology.com/projects/integrated-power-company-gas-plant-nigeria/", newsUrl: null },
  { projectName: "KivuWatt Lake Methane Gas", country: "Rwanda", region: "East Africa", technology: "Oil & Gas", dealSizeUsdMn: 142, investors: "ContourGlobal, BIO, DEG, FMO", status: "Operational", latitude: -2.06, longitude: 29.26, capacityMw: 25, announcedYear: 2009, closedYear: 2015, description: "Unique project extracting methane gas from Lake Kivu.", sourceUrl: "https://www.contourglobal.com/location/africa/", newsUrl: null },
  // EV & Clean Mobility
  { projectName: "Spiro Electric Motorcycle Fleet", country: "Benin", region: "West Africa", technology: "EV", dealSizeUsdMn: 65, investors: "Norfund, BII, Green Climate Fund, IFC", status: "Operational", latitude: 9.31, longitude: 2.32, capacityMw: null, announcedYear: 2021, closedYear: 2022, description: "Africa's largest electric motorcycle network, deploying over 50,000 e-motos across Benin, Rwanda, and Togo. Backed by leading DFIs targeting last-mile clean mobility.", sourceUrl: "https://spiro.africa/", newsUrl: "https://techcabal.com/2023/02/01/spiro-electric-motorcycles/" },
  { projectName: "BasiGo Electric Bus Fleet Nairobi", country: "Kenya", region: "East Africa", technology: "EV", dealSizeUsdMn: 10, investors: "Novastar Ventures, Factor[e] Ventures, Mobility54", status: "Operational", latitude: -1.29, longitude: 36.82, capacityMw: null, announcedYear: 2021, closedYear: 2022, description: "Kenya's first electric public bus fleet operating on Nairobi commuter routes. BasiGo provides pay-as-you-drive financing to operators and assembles buses locally.", sourceUrl: "https://basigo.africa/", newsUrl: "https://techcabal.com/2022/08/30/basigo-kenya-electric-bus/" },
  { projectName: "Ampersand Electric Motorcycles Rwanda", country: "Rwanda", region: "East Africa", technology: "EV", dealSizeUsdMn: 18, investors: "Novastar Ventures, Equator, Shell Foundation, EIB", status: "Operational", latitude: -1.94, longitude: 29.87, capacityMw: null, announcedYear: 2019, closedYear: 2021, description: "Rwanda-based electric motorcycle startup providing battery-swap enabled e-motos to commercial motorcycle taxi drivers. Largest e-moto fleet in Rwanda.", sourceUrl: "https://ampersand.solar/", newsUrl: "https://www.bbc.com/news/business-65613461" },
  { projectName: "Roam Electric Mobility Kenya", country: "Kenya", region: "East Africa", technology: "EV", dealSizeUsdMn: 24, investors: "Mobility54, Novastar Ventures, Cipla Foundation, Equator", status: "Operational", latitude: -1.28, longitude: 36.83, capacityMw: null, announcedYear: 2020, closedYear: 2022, description: "Nairobi-based EV manufacturer producing electric motorcycles and buses for East African markets, including the Roam Air motorcycle and Roam Move electric bus.", sourceUrl: "https://roamelectric.com/", newsUrl: "https://techcrunch.com/2022/06/13/kenyas-roam-electric-raises-24m/" },
  { projectName: "Stellantis EV Assembly Hub Morocco", country: "Morocco", region: "North Africa", technology: "EV", dealSizeUsdMn: 330, investors: "Stellantis, Government of Morocco, European Investment Bank", status: "Under Construction", latitude: 34.26, longitude: -6.58, capacityMw: null, announcedYear: 2023, closedYear: null, description: "Stellantis transforming its Kenitra plant into a dedicated EV assembly hub targeting European and African markets, part of Morocco's ambition to become a regional EV manufacturing base.", sourceUrl: "https://www.stellantis.com/en/news/press-releases/2023", newsUrl: "https://www.reuters.com/business/autos-transportation/stellantis-sign-agreement-morocco-ev-production-2023-01-31/" },
  { projectName: "ZUPCO Electric Bus Programme Zimbabwe", country: "Zimbabwe", region: "Southern Africa", technology: "EV", dealSizeUsdMn: 40, investors: "Government of Zimbabwe, Yutong Bus Co", status: "Operational", latitude: -17.83, longitude: 31.05, capacityMw: null, announcedYear: 2022, closedYear: 2023, description: "Zimbabwe United Passenger Company deployed a fleet of electric buses from Yutong as part of urban transport electrification in Harare and Bulawayo.", sourceUrl: "https://www.herald.co.zw/zupco-electric-buses/", newsUrl: null },
];

async function seed() {
  console.log("Seeding energy investment projects...");
  const existing = await db.select({ count: sql<number>`count(*)::int` }).from(projectsTable);
  if (existing[0].count > 0) {
    console.log(`Database already has ${existing[0].count} projects. Skipping seed.`);
    return;
  }

  await db.insert(projectsTable).values(projects);
  console.log(`Inserted ${projects.length} energy investment projects.`);
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
