import { Resend } from "resend";
import { db, userEmailsTable, newslettersTable } from "@workspace/db";
import { eq } from "drizzle-orm";

const FROM = "AfriEnergy Insights <insights@send.afrienergytracker.io>";

function chunkArray<T>(arr: T[], size: number): T[][] {
  const chunks: T[][] = [];
  for (let i = 0; i < arr.length; i += size) {
    chunks.push(arr.slice(i, i + size));
  }
  return chunks;
}

function markdownToHtmlSimple(md: string): string {
  return md
    .replace(/^## (.+)$/gm, '<h2 style="color:#1a365d;font-size:20px;margin:32px 0 12px;padding-bottom:8px;border-bottom:2px solid #00e676;">$1</h2>')
    .replace(/^### (.+)$/gm, '<h3 style="color:#2d3748;font-size:16px;margin:20px 0 8px;">$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/^- (.+)$/gm, '<li style="margin:4px 0;color:#4a5568;">$1</li>')
    .replace(/(<li[^>]*>[\s\S]*?<\/li>\s*)+/g, '<ul style="padding-left:20px;margin:12px 0;">$&</ul>')
    .replace(/\n\n/g, '</p><p style="color:#4a5568;line-height:1.7;margin:12px 0;">')
    .replace(/^(?!<[h|u|l])/gm, '')
}

function buildNewsletterEmailHtml(newsletter: {
  title: string;
  content: string;
  editionNumber: number;
  id: number;
}): string {
  const bodyContent = markdownToHtmlSimple(newsletter.content);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${newsletter.title}</title>
</head>
<body style="margin:0;padding:0;background:#f7fafc;font-family:Arial,sans-serif;">

<table width="100%" cellpadding="0" cellspacing="0" style="background:#f7fafc;">
<tr><td align="center" style="padding:24px 16px;">
<table width="100%" style="max-width:680px;" cellpadding="0" cellspacing="0">

  <!-- Header -->
  <tr><td style="background:#0b0f1a;border-radius:12px 12px 0 0;padding:32px 40px;">
    <table width="100%">
      <tr>
        <td>
          <div style="color:#00e676;font-size:11px;font-weight:700;letter-spacing:3px;text-transform:uppercase;margin-bottom:8px;">Africa Energy Pulse</div>
          <div style="color:#ffffff;font-size:28px;font-weight:800;line-height:1.2;">AfriEnergy Insights</div>
          <div style="color:#94a3b8;font-size:13px;margin-top:6px;">Edition #${newsletter.editionNumber} &nbsp;·&nbsp; ${new Date().toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" })}</div>
        </td>
        <td align="right" style="vertical-align:top;">
          <div style="background:#00e676;color:#0b0f1a;font-size:10px;font-weight:700;padding:6px 12px;border-radius:20px;letter-spacing:1px;white-space:nowrap;">AI-POWERED INTELLIGENCE</div>
        </td>
      </tr>
    </table>
  </td></tr>

  <!-- Content -->
  <tr><td style="background:#ffffff;padding:40px;">
    <p style="color:#4a5568;line-height:1.7;margin:0 0 24px;">
      ${bodyContent}
    </p>
  </td></tr>

  <!-- Data disclaimer -->
  <tr><td style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:16px 24px;margin:0 40px 24px;">
    <p style="color:#166534;font-size:12px;margin:0;">
      ⚠️ <strong>AI-Generated Analysis:</strong> This newsletter is generated by AI from the AfriEnergy Tracker database. While grounded in real tracked data, AI interpretation may contain errors. Always verify critical figures against source data.
    </p>
  </td></tr>

  <!-- Footer -->
  <tr><td style="background:#1e293b;border-radius:0 0 12px 12px;padding:24px 40px;">
    <table width="100%">
      <tr>
        <td style="color:#94a3b8;font-size:12px;line-height:1.6;">
          <p style="margin:0 0 8px;"><strong style="color:#e2e8f0;">AfriEnergy Tracker</strong> by Africa Energy Pulse</p>
          <p style="margin:0;">You are receiving this because you signed up for AfriEnergy Insights.</p>
        </td>
        <td align="right" style="vertical-align:top;">
          <a href="https://afrienergytracker.io/energy-tracker/insights" style="color:#00e676;font-size:12px;text-decoration:none;display:block;margin-bottom:8px;">View on web →</a>
          <a href="{{UNSUBSCRIBE_URL}}" style="color:#64748b;font-size:11px;text-decoration:underline;">Unsubscribe</a>
        </td>
      </tr>
    </table>
  </td></tr>

</table>
</td></tr>
</table>
</body>
</html>`;
}

export async function dispatchNewsletter(newsletterId: number): Promise<number> {
  if (!process.env.RESEND_API_KEY) {
    console.log("[EmailDispatch] No RESEND_API_KEY configured — skipping email dispatch");
    return 0;
  }

  const resend = new Resend(process.env.RESEND_API_KEY);

  // Get the newsletter
  const [newsletter] = await db
    .select()
    .from(newslettersTable)
    .where(eq(newslettersTable.id, newsletterId))
    .limit(1);

  if (!newsletter) throw new Error(`Newsletter ${newsletterId} not found`);

  // Get subscribed users
  const subscribers = await db
    .select({ email: userEmailsTable.email, unsubscribeToken: userEmailsTable.unsubscribeToken })
    .from(userEmailsTable)
    .where(eq(userEmailsTable.newsletterOptIn, true));

  if (subscribers.length === 0) {
    console.log("[EmailDispatch] No subscribers to send to");
    return 0;
  }

  const htmlTemplate = buildNewsletterEmailHtml({
    title: newsletter.title,
    content: newsletter.content,
    editionNumber: newsletter.editionNumber,
    id: newsletter.id,
  });

  const batches = chunkArray(subscribers, 100);
  let sent = 0;

  for (const batch of batches) {
    try {
      const emails = batch.map(sub => ({
        from: FROM,
        to: sub.email,
        subject: newsletter.title,
        html: htmlTemplate.replace(
          "{{UNSUBSCRIBE_URL}}",
          `https://afrienergytracker.io/api/newsletter/unsubscribe?token=${sub.unsubscribeToken ?? ""}`
        ),
      }));

      await resend.batch.send(emails);
      sent += batch.length;
    } catch (err) {
      console.error("[EmailDispatch] Batch send error:", (err as Error).message);
    }
  }

  // Update newsletter as sent
  await db
    .update(newslettersTable)
    .set({ sentAt: new Date(), recipientCount: sent, status: "sent" })
    .where(eq(newslettersTable.id, newsletterId));

  // Update last_newsletter_sent_at for all recipients
  await db
    .update(userEmailsTable)
    .set({ lastNewsletterSentAt: new Date() })
    .where(eq(userEmailsTable.newsletterOptIn, true));

  console.log(`[EmailDispatch] Sent edition #${newsletter.editionNumber} to ${sent} subscribers`);
  return sent;
}
