import { Router, type IRouter } from "express";
import healthRouter from "./health";
import projectsRouter from "./projects";
import statsRouter from "./stats";
import scraperRouter from "./scraper.js";
import adminRouter from "./admin.js";
import authRouter from "./auth.js";
import exportRouter from "./export.js";
import nlqRouter from "./nlq.js";
import watchesRouter from "./watches.js";
import savedSearchesRouter from "./saved-searches.js";
import apiKeysRouter from "./api-keys.js";
import institutionalRouter from "./institutional.js";
import seoRouter from "./seo.js";
import reviewRouter from "./review.js";
import chatRouter from "./chat.js";
import newsletterRouter from "./newsletter.js";
import reviewerAuthRouter from "./reviewer-auth.js";
import adminReviewersRouter from "./admin-reviewers.js";
import adaptersRouter from "./adapters.js";
import contributorAuthRouter from "./contributor-auth.js";
import contributionsRouter from "./contributions.js";

const router: IRouter = Router();

router.use(authRouter);
router.use(adminRouter);
router.use(healthRouter);
router.use(projectsRouter);
router.use(statsRouter);
router.use(scraperRouter);
router.use(exportRouter);
router.use(nlqRouter);
router.use(watchesRouter);
router.use(savedSearchesRouter);
router.use(apiKeysRouter);
router.use(institutionalRouter);
router.use(seoRouter);
router.use(reviewRouter);
router.use(chatRouter);
router.use(newsletterRouter);
router.use(reviewerAuthRouter);
router.use(adminReviewersRouter);
router.use(adaptersRouter);
router.use(contributorAuthRouter);
router.use(contributionsRouter);

export default router;
